#!/bin/sh

valgrind -v --leak-check=full ./bin/ent-test \
	| sed -e 'g/^--/s/:/;/g'

gcov *.gcda > /dev/null

grep '#####' *.gcov \
	| cut -d: -f1,3,4- \
	| sed -e 's/: */:/' -e 's/\.gcov//' \
	| grep -v 'EOF' \
	> test/cov_miss_actual.txt

diff test/cov_miss_expected.txt test/cov_miss_actual.txt

